openapi: 3.0.0
info:
  title: basictest
  version: '0.1'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users-userId
      description: 'Shows the user of the given {userId}'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      parameters: []
    put:
      summary: ''
      operationId: put-users-userId
      responses:
        '200':
          description: OK
      description: Updates one user
    delete:
      summary: ''
      operationId: delete-users-userId
      responses:
        '200':
          description: OK
      description: Delete one user
  '/users/{userId}/edit':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
      operationId: get-users
      description: Returns all users
      parameters:
        - schema:
            type: string
          in: query
          name: username
          description: ''
        - schema:
            type: string
          in: query
          name: createdAtFrom
        - schema:
            type: string
          in: query
          name: createdAtTo
        - schema:
            type: string
          in: query
          name: updatedAtFrom
        - schema:
            type: string
          in: query
          name: updatedAtTo
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
      description: Stores/Adds a user
  /questions:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-questions
      description: Returns all questions
      parameters:
        - schema:
            type: string
            default: 'null'
          in: query
          name: questionId
        - schema:
            type: string
            format: date-time
          in: query
          name: createdAtFrom
        - schema:
            type: string
            format: date-time
          in: query
          name: createdAtTo
        - schema:
            type: string
          in: query
          name: createdBy
          description: The creator of the questions
        - schema:
            type: string
          in: query
  /units:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    name:
                      type: string
                    unitShorthand:
                      type: string
                    modul:
                      type: string
                    parent:
                      type:
                        - string
                        - 'null'
              examples:
                example-1:
                  value:
                    - uuid: 8a5ed9b7-490f-445e-91ee-208122eba4b3
                      name: Einf√ºhrung
                      shorthand: '1'
                      modul: 1a265919-b923-4890-b879-e79d9e0cd968
                      parent: null
                    - uuid: ff354df4-90da-47de-b54a-fae1bfd4323a
                      name: Motivation
                      shorthand: '1.1'
                      modul: 1a265919-b923-4890-b879-e79d9e0cd968
                      parent: 8a5ed9b7-490f-445e-91ee-208122eba4b3
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-units
      description: Returns an array of 'Unit'-objects
      security:
        - Bearer: []
      parameters:
        - schema:
            type: string
          in: query
          name: uuid
          description: Universal unique identifier for a 'Unit'
        - schema:
            type: string
          in: query
          name: name
          description: Name of a 'Unit'
        - schema:
            type: string
          in: query
    post:
      summary: ''
      operationId: post-units
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
      description: Creates 'Unit'-objects
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: ''
              minItems: 1
              uniqueItems: true
              items:
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  shorthand:
                    type: string
                    minLength: 1
                  modul:
                    type: string
                    minLength: 1
                  parent:
                    type:
                      - string
                      - 'null'
                    minLength: 1
                required:
                  - name
                  - shorthand
                  - modul
                  - parent
            examples: {}
        description: ''
    put:
      summary: ''
      operationId: put-units
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Updates an array of 'Unit'-objects
      security:
        - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: ''
              minItems: 1
              uniqueItems: true
              items:
                type: object
                properties:
                  uuid:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  shorthand:
                    type: string
                    minLength: 1
                  modul:
                    type: string
                    minLength: 1
                  parent:
                    type:
                      - string
                      - 'null'
                    minLength: 1
                required:
                  - uuid
                  - name
                  - shorthand
                  - modul
                  - parent
            examples:
              example-1:
                value:
                  uuid: string
                  name: string
                  shorthand: string
                  modul: string
                  parent: string
    delete:
      summary: ''
      operationId: delete-units
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Removes an array of 'Unit'-objects
      parameters:
        - schema:
            type: string
          in: query
          name: uuid
  '/units/{uuid}':
    parameters:
      - schema:
          type: string
        name: uuid
        in: path
        description: Univeral Unique Identifier for a 'Unit'
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users-userId-edit
      description: |-
        Get the form for editing

        ## TODO: check if we need do active disable this
  /users/create:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users-create
      description: |-
        Get the create form

        ## TODO: Need to disable this as well?
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  uuid:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  unitShorthand:
                    type: string
                    minLength: 1
                  modul:
                    type: string
                  parent:
                    type:
                      - string
                      - 'null'
                required:
                  - uuid
                  - name
                  - unitShorthand
                  - modul
              examples:
                example-1:
                  value:
                    uuid: 8a5ed9b7-490f-445e-91ee-208122eba4b3
                    name: Einf√ºhrung
                    shorthand: '1'
                    modul: 1a265919-b923-4890-b879-e79d9e0cd968
                    parent: null
      operationId: get-units-uuid
      description: Returns a single 'Unit'
      security:
        - Bearer: []
components:
  schemas:
    User:
      title: User
      type: object
      x-examples:
        example-1:
          id: 0504e723-f588-46a5-b648-aa3f3b93fd50
          email: test@gemeisstudieren.de
          username: gemeinsam2020
          firstName: Gemeinsame
          lastName: Studieren
          createdAt: '2020-10-12 16:17:00+02:00'
          updatedAt: '2020-10-12 16:17:00+02:00'
      description: ''
      properties:
        id:
          type: integer
        email:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        password:
          type: string
        token:
          type: string
        tokenExpiresAt:
          type: string
      required:
        - id
        - email
    Unit:
      title: Unit
      type: object
      x-examples:
        example-1:
          id: 5
          uuid: 8a5ed9b7-490f-445e-91ee-208122eba4b3
          name: Einf√ºhrung
          shorthand: '1'
          modul: 1a265919-b923-4890-b879-e79d9e0cd968
          parent: null
        example-2:
          id: 25
          uuid: ff354df4-90da-47de-b54a-fae1bfd4323a
          name: Motivation
          shorthand: '1.1'
          modul: 1a265919-b923-4890-b879-e79d9e0cd968
          parent: 8a5ed9b7-490f-445e-91ee-208122eba4b3
      description: The model of a 'Unit'.
      properties:
        id:
          description: Primary key of a 'Unit'
          type: number
        uuid:
          type: string
          description: Universally Unique Identifier for a 'Unit'
        name:
          type: string
          description: Name of a 'Unit'
        shorthand:
          type: string
          description: Short presentation of a 'Unit'
        modul:
          description: Contains the id of the referenced 'Modul'
          type: string
        parent:
          description: Contains the id of the parent 'Unit'
          type:
            - string
            - 'null'
        createdAt:
          type: string
          description: Contains datetime of 'Unit'-creation
        updatedAt:
          type: string
          description: Contains datetime of 'Unit'-update
  securitySchemes:
    Bearer:
      name: token
      type: apiKey
      in: query
security:
  - Bearer: []
